"""Add LearningObjective table

Revision ID: a00c570068ba
Revises: dadf1d83d8f9
Create Date: 2025-07-24 13:54:42.910686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00c570068ba'
down_revision = 'dadf1d83d8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=10), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.Text(), nullable=True),
    sa.Column('course', sa.Text(), nullable=True),
    sa.Column('external', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_key', 'level', name='uq_module_level')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_objective')
    # ### end Alembic commands ###
