"""Add user_level to Progress

Revision ID: a60874514fbf
Revises: a00c570068ba
Create Date: 2025-07-29 18:37:05.274389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60874514fbf'
down_revision = 'a00c570068ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_level', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('user_level')

    # ### end Alembic commands ###
